In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from google.colab import files

uploaded = files.upload()

Saving bookstoscrape.csv to bookstoscrape (1).csv

In [5]:
df = pd.read_csv("/content/bookstoscrape.csv", sep=';')

df.head()

,titulo,precio,cantidad_stock,categoria,rating
0,A Light in the Attic,51.77,22,poetry,3
1,Tipping the Velvet,53.74,20,historical fiction,1
2,Soumission,50.10,20,fiction,1
3,Sharp Objects,47.82,20,mystery,4
4,Sapiens: A Brief History of Humankind,54.23,20,history,5

In [6]:
df.shape

(1000, 5)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   titulo          1000 non-null   object
 1   precio          1000 non-null   float64
 2   cantidad_stock  1000 non-null   int64
 3   categoria       1000 non-null   object
 4   rating          1000 non-null   int64
dtypes: float64(1), int64(2), object(2)
memory usage: 39.2+ KB

In [8]:
df.columns

Index(['titulo', 'precio', 'cantidad_stock', 'categoria', 'rating'], dtype='object')

In [9]:
df.isnull().sum()

titulo            0
precio            0
cantidad_stock    0
categoria         0
rating            0
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df.drop_duplicates(inplace=True)

In [12]:
df.describe()

           precio  cantidad_stock       rating
count  1000.00000     1000.000000  1000.000000
mean     35.07035        8.585000     2.923000
std      14.44669        5.654622     1.434967
min      10.00000        1.000000     1.000000
25%      22.10750        3.000000     2.000000
50%      35.98000        7.000000     3.000000
75%      47.45750       14.000000     4.000000
max      59.99000       22.000000     5.000000

In [14]:
df["rating"].value_counts()

rating
1    226
3    203
5    196
2    196
4    179
Name: count, dtype: int64

In [16]:
df.loc[df["precio"].idxmax()]

titulo            The Perfect Play (Play by Play #1)
precio                                         59.99
cantidad_stock                                     4
categoria                                    romance
rating                                             3
Name: 648, dtype: object

In [19]:
df["precio"].mean()

np.float64(35.07035)

In [21]:
df.loc[df["precio"].idxmin()]

titulo            An Abundance of Katherines
precio                                  10.0
cantidad_stock                             5
categoria                        young adult
rating                                     5
Name: 638, dtype: object